from pathlib import Path
import re

path = Path("WH40k_11th.html")
text = path.read_text(encoding="utf-8")


def replace_once(old, new, label):
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected 1 match, found {count}")
    text = text.replace(old, new, 1)


# Sequential release metadata.
replace_once("<title>WH40k 11th V31.148</title>", "<title>WH40k 11th V31.149</title>", "title")
replace_once(
    "The current baseline is WH40k_11th_V31.148;",
    "The current baseline is WH40k_11th_V31.149;",
    "baseline",
)
replace_once('const APP_VERSION = "31.148";', 'const APP_VERSION = "31.149";', "APP_VERSION")
replace_once("version: 'V31.148',", "version: 'V31.149',", "quality version")

# Phase 3: project Ability Active into a detached copy of the current roster
# entry, then let the existing effective-weapon engine apply the structured
# Tag rules and their existing Range/Melee scope. The saved roster Tag state is
# never mutated by this New View calculation.
weapon_helper = r'''    function getAlternateViewEffectiveWeaponProfile(entry, unit, weapon, roster) {
      if (!entry || !unit || !weapon) return weapon || {};

      const projectedEntry = {
        ...entry,
        abilityTagStates: JSON.parse(JSON.stringify(entry.abilityTagStates || {}))
      };

      getAbilitiesForRosterEntry(entry, unit)
        .filter(ability => ability && !ability.isMissingLink)
        .forEach((ability, sequence) => {
          const sourceItem = getAbilitySourceItem(ability) || ability;
          const effectiveItem = getRosterEntryEffectiveAbility(entry, sourceItem) || sourceItem;
          const rawItemKey = getAbilityItemEditKey(sourceItem) || sourceItem.abilityId || sourceItem.name || sequence;
          const itemKey = String(rawItemKey ?? "").trim();
          const abilityActive = Boolean(
            itemKey && window.isAlternateViewAbilityMechanicallyEligible(entry.entryId, itemKey)
          );
          const defaultOn = getRosterTaggedSourceDefaultActive("ability", sourceItem);

          // In New View the Ability title is the master mechanical switch for
          // every structured Tag owned by that Ability. The existing weapon
          // engine decides whether each Tag applies to this Range/Melee weapon.
          getAbilityProtectedModifierTagAssignments(effectiveItem).forEach(assignment => {
            setRosterEntryAbilityTagState(
              projectedEntry,
              sourceItem,
              assignment.tag,
              abilityActive,
              defaultOn,
              assignment.category
            );
          });
        });

      return getRosterEntryEffectiveWeaponProfile(projectedEntry, unit, weapon, roster) || weapon;
    };

'''
weapon_helper_anchor = "    window.toggleAlternateViewAbilityTag = function(payload = {}) {"
if text.count(weapon_helper_anchor) != 1:
    raise SystemExit("V31.149 weapon helper anchor missing")
text = text.replace(weapon_helper_anchor, weapon_helper + weapon_helper_anchor, 1)

# New View weapon projection now displays the effective profile generated by
# the existing weapon engine under the Ability Active gate. Weapon identity,
# quantity, native Tags, Tag state, scope, and all layout data remain unchanged.
old_weapon_map = r'''        weapons: weapons.map(weapon => {
          const range = String(weapon.range ?? "").trim();
          const melee = range === "-" || range.toLowerCase() === "melee" || /\(melee\)/i.test(String(weapon.name || ""));
          const scope = melee ? "MELEE" : (range ? "SHOOT" : "OTHER");
          const tags = splitWeaponAbilities(weapon.weaponAbility);
          const tagStates = tags.map(tag => {
            const locked = isInnateWeaponAbilityTag(weapon, tag);
            return {
              tag: String(tag || ""),
              active: locked ? true : getRosterEntryWeaponTagState(entry, weapon, tag, true),
              locked: Boolean(locked)
            };
          });
          return {
            weaponId: String(weapon.weaponId || ""),
            quantity: entry && unit ? getRosterWeaponQuantity(entry, unit, weapon) : 0,
            name: String(weapon.name || weapon.weaponId || ""),
            range,
            attacks: String(weapon.attacks ?? ""),
            skill: String(weapon.skill ?? ""),
            strength: String(weapon.strength ?? ""),
            ap: String(weapon.ap ?? ""),
            damage: String(weapon.damage ?? ""),
            tags,
            tagStates,
            scope
          };
        })'''
new_weapon_map = r'''        weapons: weapons.map(weapon => {
          const range = String(weapon.range ?? "").trim();
          const melee = range === "-" || range.toLowerCase() === "melee" || /\(melee\)/i.test(String(weapon.name || ""));
          const scope = melee ? "MELEE" : (range ? "SHOOT" : "OTHER");
          const tags = splitWeaponAbilities(weapon.weaponAbility);
          const tagStates = tags.map(tag => {
            const locked = isInnateWeaponAbilityTag(weapon, tag);
            return {
              tag: String(tag || ""),
              active: locked ? true : getRosterEntryWeaponTagState(entry, weapon, tag, true),
              locked: Boolean(locked)
            };
          });
          const effectiveWeapon = entry && unit
            ? getAlternateViewEffectiveWeaponProfile(entry, unit, weapon, roster)
            : weapon;
          return {
            weaponId: String(weapon.weaponId || ""),
            quantity: entry && unit ? getRosterWeaponQuantity(entry, unit, weapon) : 0,
            name: String(weapon.name || weapon.weaponId || ""),
            range,
            attacks: String(effectiveWeapon.attacks ?? weapon.attacks ?? ""),
            skill: String(effectiveWeapon.skill ?? weapon.skill ?? ""),
            strength: String(effectiveWeapon.strength ?? weapon.strength ?? ""),
            ap: String(effectiveWeapon.ap ?? weapon.ap ?? ""),
            damage: String(effectiveWeapon.damage ?? weapon.damage ?? ""),
            tags,
            tagStates,
            scope
          };
        })'''
replace_once(old_weapon_map, new_weapon_map, "New View effective Weapon projection")

note = '''  <!--
    CHANGE NOTE - WH40k_11th_V31.149
    Scope: Phase 3 New View Ability-driven Weapon mechanics. Active Ability titles now force their Ability-owned structured Tags on in a detached New View weapon projection; inactive Ability titles force those Tags off, regardless of legacy per-Tag saved state or CSV Default_Active. The existing effective-weapon engine then applies the established Tag rules and Range/Melee scope to A, BS/WS, S, AP, and D for the matching weapon. The real roster Tag state is not mutated. Phase 2 Unit-stat behavior remains unchanged, and Probable is not run or refreshed by this phase.
    Risk areas: New View Weapon profile projection only. Old View, persistent Tag state, CSV data, Unit-stat Phase 2 behavior, Probable execution, grid/layout, typography, colors, Cards, Waha, FIX mode, and Version controls are unchanged.
  -->

'''
marker = "  <!--\n    CHANGE NOTE - WH40k_11th_V31.148\n"
if text.count(marker) != 1:
    raise SystemExit("V31.148 change-note insertion marker missing")
text = text.replace(marker, note + marker, 1)

# Keep only the five newest detailed V31 change notes.
notes = list(
    re.finditer(
        r"\n?  <!--\n    CHANGE NOTE - WH40k_11th_V31\.\d+\n.*?\n  -->\n",
        text,
        re.S,
    )
)
for match in reversed(notes[5:]):
    text = text[: match.start()] + text[match.end() :]

# Acceptance: Phase 3 must use the existing effective-weapon engine under the
# New View Ability master gate, and must not introduce Probable work.
for expected in [
    "function getAlternateViewEffectiveWeaponProfile(entry, unit, weapon, roster)",
    "window.isAlternateViewAbilityMechanicallyEligible(entry.entryId, itemKey)",
    "getRosterEntryEffectiveWeaponProfile(projectedEntry, unit, weapon, roster)",
    "const effectiveWeapon = entry && unit",
    "attacks: String(effectiveWeapon.attacks ?? weapon.attacks ?? \"\")",
    "skill: String(effectiveWeapon.skill ?? weapon.skill ?? \"\")",
    "strength: String(effectiveWeapon.strength ?? weapon.strength ?? \"\")",
    "ap: String(effectiveWeapon.ap ?? weapon.ap ?? \"\")",
    "damage: String(effectiveWeapon.damage ?? weapon.damage ?? \"\")",
    "<title>WH40k 11th V31.149</title>",
    "The current baseline is WH40k_11th_V31.149;",
    'const APP_VERSION = "31.149";',
    "version: 'V31.149',",
    "CHANGE NOTE - WH40k_11th_V31.149",
]:
    if expected not in text:
        raise SystemExit("V31.149 acceptance failed: " + expected)

helper_start = text.find("    function getAlternateViewEffectiveWeaponProfile(")
helper_end = text.find("    window.toggleAlternateViewAbilityTag = function(payload = {}) {", helper_start)
if helper_start < 0 or helper_end < 0:
    raise SystemExit("V31.149 helper bounds missing")
helper_body = text[helper_start:helper_end]
for forbidden in [
    "renderProbablePanel(",
    "refreshProbableSection(",
    "renderNewViewRosterRows(",
    "getAlternateViewRosterRows(",
]:
    if forbidden in helper_body:
        raise SystemExit("V31.149 Phase 3 scope violation: " + forbidden)

path.write_text(text, encoding="utf-8")
print("Built V31.149: Ability Active now gates New View effective Weapon profiles")
